name: empresas_flutter
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  get: ^4.1.4
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
      - assets/images/

